name: Python Package using Conda

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - run : echo "Rodando no Ubuntu"
    - name: Set up Python 3.10
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
        cache: pip
        architecture: x64
        cache-dependency-path: '${{ github.workspace }}/requirements.txt'
    
