name: Python Package using Conda

on:
  push:
    branches:
      - '**' 

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - run : echo "Rodando no Ubuntu"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
        cache: pip
        architecture: x64
        cache-dependency-path: '${{ github.workspace }}/requirements.txt'

    
      
    - run: | 
        echo "Rodando testes"
        cd ${{github.workspace}}
        pip install -r requirements.txt
        cd ${{github.workspace}}/tests
        python -m unittest